apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
- ../base

patchesStrategicMerge:
- deployment-patch.yaml

patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: backend

patchesJson6902:
  - target:
      version: v1
      kind: ServiceAccount
      name: backend-dev50-rolldupapp-com
    path: service-account-patch.yaml
