apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
- ../base
patchesStrategicMerge:
- deployment-patch.yaml
- service-account-patch.yaml
- pdb-patch.yaml
patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: backend
