INSERT INTO users (username, user_rank, join_date) values ('dankybud', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('fuzzyg', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('skunkmaster', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Sarah Connor', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Marty McFly', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Zeaphod Beablebrox', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('John McClane', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Ellen Ripley', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('John Snow', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Walter White', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Wednesday Adams', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Indigo Montoya', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Samwise Gamgee', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Donnie Darko', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('James T. Kirk', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Tony Montana', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Ace Ventura', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Shaun Riley', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Ferris Bueller', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Rocky Balboa', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Mal Reynolds', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Jules Winnfield', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Peter Venkman', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Forest Gump', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Patrick Bateman', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Ron Burgandy', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Indiana Jones', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('The Dude', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Tyler Durden', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Bruce Wayne', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Han Solo', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('James Bond', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Jack Sparow', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Derek Zoolander', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Elle Woods', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Penny Lane', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Buzz Lightyear', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('John Wick', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Dennis Quade', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Peter Griffin', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Philip J. Fry', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Jay Gatsby', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Mary Poppins', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Peter Pan', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Tony Stark', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Kevin McAllister', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Other Barry', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Sterling Archer', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Stan Smith', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Rick Sanchez', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Zapp Branagan', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Austin Powers', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Willy Wonka', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Lando Calrissian', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Robin Hood', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('John Gault', 'coinnessoir', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Hank Hill', 'stoner', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Nathan Explosion', 'bogart', CURRENT_DATE);
INSERT INTO users (username, user_rank, join_date) values ('Andy Anderson', 'coinnessoir', CURRENT_DATE);

insert into user_settings (user_id, pronouns, birthdate, public_profile, dark_mode, pn_messages, pn_group_activities, pn_comments, pn_friend_requests, pn_recommendations, pn_newsletter)
values (61, 'He/Him', '1988-09-23', TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE);
insert into user_settings (user_id, pronouns, birthdate, public_profile, dark_mode, pn_messages, pn_group_activities, pn_comments, pn_friend_requests, pn_recommendations, pn_newsletter)
values (1, 'She/Her', '1960-01-02', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE);
insert into user_settings (user_id, pronouns, birthdate, public_profile, dark_mode, pn_messages, pn_group_activities, pn_comments, pn_friend_requests, pn_recommendations, pn_newsletter)
values (3, 'None', '2003-12-01', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);

insert into strains (name, strain, category) values('Trainwreck', 'Indica', 'Flower');
insert into strains (name, strain, category) values('Green Crack', 'Indica', 'Edible');
insert into strains (name, strain, category) values('Sour Diesel', 'Sativa', 'Flower');
insert into strains (name, strain, category) values('White Widow', 'Hybrid', 'Concentrate');
insert into strains (name, strain, category) values('Girlscout Cookies', 'Indica', 'Flower');
insert into strains (name, strain, category) values('Grandaddy Purp', 'Sativa', 'Topical');
insert into strains (name, strain, category) values('Pineapple Kush', 'Sativa', 'Cartridge');
insert into strains (name, strain, category) values('Blue Dream', 'Sativa', 'PreRoll');
insert into strains (name, strain, category) values('Skunk', 'Hybrid', 'Flower');
insert into strains (name, strain, category) values('Trainwreck', 'Indica', 'Concentrate');

insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1602168431602-9bfa3722a472?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 61, 'THC', 22, 1, 4, 'Good for back pain.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, mgs, strain_id, rating) values (current_timestamp, 'https://images.unsplash.com/photo-1609443934742-3e2383f9423f?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Y2FubmFiaXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500', 1, 'THC', 50, 2, 3);
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1589844428386-06bba62381a5?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FubmFiaXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500', 3, 'THC', 18, 3, 4, 'Here is an intentionally long review to help test with displaying the truncated view. We are allowing 300 characters per review at this time, so it might take a bit of a review to even reach the truncation itself. I think I kind of like the slightly middly-long review length though, because I ten to be long winded myself.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1503262028195-93c528f03218?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 3, 'THC', 95, 4, 5, 'Spacey');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1630678691613-0ee767e22250?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 1, 'THC', 15, 1, 2, 'Gave me mega munchies.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1589141986943-5578615fdef2?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 3, 'THC', 19, 5, 4, 'So many thc crystals. These buds were sparklier than a vampire.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1612995923001-27d03779d023?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 1, 'CBD', 6, 3, 'Eased my arthiritis.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating) values (current_timestamp, 'https://images.unsplash.com/photo-1573461160327-b450ce3d8e7f?ixlib=rb-1.2.1&raw_url=true&q=60&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjN8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 1, 'THC', 16, 3, 1);
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating) values (current_timestamp, 'https://images.unsplash.com/photo-1517773015382-e8a6414bbe50?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjJ8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 61, 'THC', 92, 7, 4);
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, mgs, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1617101815102-e5728e6685fc?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 3, 'CBD', 10, 2, 5, 'Here is an intentionally long review to help test with displaying the truncated view. We are allowing 300 characters per review at this time, so it might take a bit of a review to even reach the truncation itself. I think I kind of like the slightly middly-long review length though, because I ten to be long winded myself.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1599227705778-6427976abdc7?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 3, 'THC', 20, 1, 2, 'Here is an intentionally long review to help test with displaying the truncated view. We are allowing 300 characters per review at this time, so it might take a bit of a review to even reach the truncation itself. I think I kind of like the slightly middly-long review length though, because I ten to be long winded myself.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, strain_id, rating) values (current_timestamp, 'https://images.unsplash.com/photo-1609443935270-78d23b74b59a?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 61, 'THC', 8, 3);
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating, review) values (current_timestamp, 'https://images.unsplash.com/photo-1457573399415-1154bfe3ff71?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzh8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 1, 'THC', 17, 9, 4, 'Helped me sleep.');
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, percentage, strain_id, rating) values (current_timestamp, 'https://images.unsplash.com/photo-1626106576760-d64336d3fa5b?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDB8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 61, 'THC', 98, 10, 2);
insert into strain_logs (time_logged, pic_url, user_id, cannabinoid, strain_id, rating) values (current_timestamp, 'https://images.unsplash.com/photo-1630526974594-501cb00c10bc?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDd8fGNhbm5hYmlzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500', 3, 'THC', 8, 3);

insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(1, 4, 'Dude, nice.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(1, 5, 'This is my new favorite.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(1, 6, 'I just can''t get over how gorgeous that picture is. I mean really.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(2, 7, 'Shit is straight purple.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(3, 8, 'You are so right.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(3, 9, 'I like the way you roll.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(3, 10, 'I''ve been wanting to try this.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(3, 11, 'Are you going to eat that?', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(3, 12, 'Is it just me or do filters ruin a joint?', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(3, 13, 'Might be just you dog.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(4, 14, 'This is my new favorite.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(5, 15, 'This is my new favorite.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(6, 16, 'This is my new favorite.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(7, 17, 'This is my new favorite.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(8, 18, 'This is my new favorite.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(10, 19, 'Is it just me or do filters ruin a joint?', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(11, 20, 'Is it just me or do filters ruin a joint?', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(10, 21, 'I like the way you roll.', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(10, 22, 'Is it just me or do filters ruin a joint?', current_timestamp);
insert into strain_log_comments (log_id, owner_id, comment_message, time_logged) values(8, 23, 'Is it just me or do filters ruin a joint?', current_timestamp);
