insert into strains (name, strain, category) values('Acapulco Gold', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Alaskan Thunder Fuck', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Alice in Wonderland', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Allen Wrench', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Aloha', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Amnesia', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Amnesia Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Arabian Gold', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Arjan''s Strawberry Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Asian Fantasy', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Bay 11', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Berkely', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Black Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Blue Bayou', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Blue Satellite', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Brainstorm Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Candy Jack', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Cannalope Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Cat Piss', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Charlotte''s Web', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Chocolope', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Cracker Jack', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Crystal Coma', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Django', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Double Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Dr. Grinspoon', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Durban Poison', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Dutch Dragon', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Dutch Hawaiian', 'sativa', 'Flower');
insert into strains (name, strain, category) values('East Coast Sour Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Fire Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Frostbite', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Ghost Train Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Goldwing', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Grapefruit', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Green Candy', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Green Crack', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Green Crack Extreme', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Green Goblin', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Green Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('G Stik "Amarillo"', 'sativa', 'Flower');
insert into strains (name, strain, category) values('G Stik "Rosado"', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Hawaiian', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Sativa', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Snow', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Haze Wreck', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Hempstar', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Hydro Green Crack', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Island Sweet Skunk', 'sativa', 'Flower');
insert into strains (name, strain, category) values('J-27', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Jack Herer', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Jack Skellington', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Jack Wreck', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Jamaican Pearl', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Jean Guy', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Johnny''s Tonic', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Kaboom', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Kali Mist', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Killing Fields', 'sativa', 'Flower');
insert into strains (name, strain, category) values('King''s Bread', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Lamb''s Bread', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Laughing Buddha', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Lemon Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Lemon Jack', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Lemon G', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Lemon Sativa', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Lemon Thai', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Mako Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Malawi', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Mango Dream', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Maui', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Maui Waui', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Mexican Sativa', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Moby Dick', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Mother''s Finest', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Nevil''s Wreck', 'sativa', 'Flower');
insert into strains (name, strain, category) values('OCD', 'sativa', 'Flower');
insert into strains (name, strain, category) values('OG', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Outer Space', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Panama Red', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Pandora''s Box', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Poison Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Purple Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Q3', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Qleaner', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Rafael', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Red Congolese', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Red Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Rene', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Root Beer Kush', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sage N Sour', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Shaman', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Shangri La OG', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Shipwreck', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Silver Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Skunk #1', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sour Chocolate', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sour Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sour Flower', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sour Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sour Tangie', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Strawberry', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sugar Plum', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Super Cat Piss', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Super Green Crack', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Super Silver Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Super Snow Dog', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Super Sour Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Sweet Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Tangie', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Thai', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Thai Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Timewreck', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Triple Diesel', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Twista', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Ultimate Trainwreck', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Venice OG', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Very Berry Haze', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Voodoo', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Vortex', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Waipi''o Hapa', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Willie Nelson', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Willy Wonka', 'sativa', 'Flower');
insert into strains (name, strain, category) values('Y Griega', 'sativa', 'Flower');
insert into strains (name, strain, category) values('3X Crazy', 'indica', 'Flower');
insert into strains (name, strain, category) values('8 Ball Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('A-10', 'indica', 'Flower');
insert into strains (name, strain, category) values('Abusive OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Afghani', 'indica', 'Flower');
insert into strains (name, strain, category) values('Afghani Bullrider', 'indica', 'Flower');
insert into strains (name, strain, category) values('Afghan Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Afghan Skunk', 'indica', 'Flower');
insert into strains (name, strain, category) values('Afgoo', 'indica', 'Flower');
insert into strains (name, strain, category) values('Afgooey', 'indica', 'Flower');
insert into strains (name, strain, category) values('Alien Dawg', 'indica', 'Flower');
insert into strains (name, strain, category) values('Alien Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Ancient OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Anesthesia', 'indica', 'Flower');
insert into strains (name, strain, category) values('Aurora Indica', 'indica', 'Flower');
insert into strains (name, strain, category) values('Banana Candy', 'indica', 'Flower');
insert into strains (name, strain, category) values('Banana Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Barbara Bud', 'indica', 'Flower');
insert into strains (name, strain, category) values('Berry Noir', 'indica', 'Flower');
insert into strains (name, strain, category) values('Big Bud', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blackberry Hashplant', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blackberry Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Black Cherry Soda', 'indica', 'Flower');
insert into strains (name, strain, category) values('Black Diamond', 'indica', 'Flower');
insert into strains (name, strain, category) values('Black Label Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blackwater', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blueberry', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blueberry Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blueberry Waltz', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blue Cheese', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blue God', 'indica', 'Flower');
insert into strains (name, strain, category) values('Blue Moonshine', 'indica', 'Flower');
insert into strains (name, strain, category) values('Bubba Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Bubba OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Buddha''s Sister', 'indica', 'Flower');
insert into strains (name, strain, category) values('Butterscotch', 'indica', 'Flower');
insert into strains (name, strain, category) values('Candy Cane', 'indica', 'Flower');
insert into strains (name, strain, category) values('Cactus', 'indica', 'Flower');
insert into strains (name, strain, category) values('Cadillac Purple', 'indica', 'Flower');
insert into strains (name, strain, category) values('Cheese Quake', 'indica', 'Flower');
insert into strains (name, strain, category) values('Chem Scout', 'indica', 'Flower');
insert into strains (name, strain, category) values('Cherry Kola', 'indica', 'Flower');
insert into strains (name, strain, category) values('Chocolate Chunk', 'indica', 'Flower');
insert into strains (name, strain, category) values('Church OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Corleone Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Critical Mass', 'indica', 'Flower');
insert into strains (name, strain, category) values('Danky Doodle', 'indica', 'Flower');
insert into strains (name, strain, category) values('Dark Star', 'indica', 'Flower');
insert into strains (name, strain, category) values('Darth Vader OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Death Star', 'indica', 'Flower');
insert into strains (name, strain, category) values('Death Star OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Deep Purple', 'indica', 'Flower');
insert into strains (name, strain, category) values('Denver Maple', 'indica', 'Flower');
insert into strains (name, strain, category) values('Devil Fruit', 'indica', 'Flower');
insert into strains (name, strain, category) values('Diablo', 'indica', 'Flower');
insert into strains (name, strain, category) values('Diamond OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Digweed', 'indica', 'Flower');
insert into strains (name, strain, category) values('DJ Short Blueberry', 'indica', 'Flower');
insert into strains (name, strain, category) values('Domino', 'indica', 'Flower');
insert into strains (name, strain, category) values('Dynamite', 'indica', 'Flower');
insert into strains (name, strain, category) values('Edelweiss', 'indica', 'Flower');
insert into strains (name, strain, category) values('El Jeffe', 'indica', 'Flower');
insert into strains (name, strain, category) values('Enigma', 'indica', 'Flower');
insert into strains (name, strain, category) values('Endless Sky', 'indica', 'Flower');
insert into strains (name, strain, category) values('Eran Almog', 'indica', 'Flower');
insert into strains (name, strain, category) values('Freezeland', 'indica', 'Flower');
insert into strains (name, strain, category) values('Frosty', 'indica', 'Flower');
insert into strains (name, strain, category) values('Fucking Incredible', 'indica', 'Flower');
insert into strains (name, strain, category) values('Funky Monkey', 'indica', 'Flower');
insert into strains (name, strain, category) values('G13', 'indica', 'Flower');
insert into strains (name, strain, category) values('Godberry', 'indica', 'Flower');
insert into strains (name, strain, category) values('God Bud', 'indica', 'Flower');
insert into strains (name, strain, category) values('Godfather OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('God''s Gift', 'indica', 'Flower');
insert into strains (name, strain, category) values('Gog & Magog', 'indica', 'Flower');
insert into strains (name, strain, category) values('Granddaddy Purple', 'indica', 'Flower');
insert into strains (name, strain, category) values('Grand Hindu', 'indica', 'Flower');
insert into strains (name, strain, category) values('Grape Ape', 'indica', 'Flower');
insert into strains (name, strain, category) values('Grape Crush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Grape Skunk', 'indica', 'Flower');
insert into strains (name, strain, category) values('Gravity', 'indica', 'Flower');
insert into strains (name, strain, category) values('G Stik "RED"', 'indica', 'Flower');
insert into strains (name, strain, category) values('G Stik "Violeta"', 'indica', 'Flower');
insert into strains (name, strain, category) values('Guido Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Gumbo', 'indica', 'Flower');
insert into strains (name, strain, category) values('Haoma', 'indica', 'Flower');
insert into strains (name, strain, category) values('Hashberry', 'indica', 'Flower');
insert into strains (name, strain, category) values('Hash Plant', 'indica', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Delight', 'indica', 'Flower');
insert into strains (name, strain, category) values('Herojuana', 'indica', 'Flower');
insert into strains (name, strain, category) values('Hindu Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Hog', 'indica', 'Flower');
insert into strains (name, strain, category) values('Hog''s Breath', 'indica', 'Flower');
insert into strains (name, strain, category) values('Hollands Hope', 'indica', 'Flower');
insert into strains (name, strain, category) values('Ingrid', 'indica', 'Flower');
insert into strains (name, strain, category) values('Jagermeister', 'indica', 'Flower');
insert into strains (name, strain, category) values('Jesus OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('JT15', 'indica', 'Flower');
insert into strains (name, strain, category) values('Jupiter Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Jupiter OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('K Train', 'indica', 'Flower');
insert into strains (name, strain, category) values('Kandahar', 'indica', 'Flower');
insert into strains (name, strain, category) values('King Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('King Louis', 'indica', 'Flower');
insert into strains (name, strain, category) values('Kosher Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Kryptonite', 'indica', 'Flower');
insert into strains (name, strain, category) values('Kushadelic', 'indica', 'Flower');
insert into strains (name, strain, category) values('Kush Berry', 'indica', 'Flower');
insert into strains (name, strain, category) values('LA OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Larry OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Lavender Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Lemon OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Lions Gate', 'indica', 'Flower');
insert into strains (name, strain, category) values('Liquid Butter', 'indica', 'Flower');
insert into strains (name, strain, category) values('Louis XIII', 'indica', 'Flower');
insert into strains (name, strain, category) values('Madagascar', 'indica', 'Flower');
insert into strains (name, strain, category) values('Mango', 'indica', 'Flower');
insert into strains (name, strain, category) values('Maple Leaf Indica', 'indica', 'Flower');
insert into strains (name, strain, category) values('Mars OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Master Bubba', 'indica', 'Flower');
insert into strains (name, strain, category) values('Master Jedi', 'indica', 'Flower');
insert into strains (name, strain, category) values('Master Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Matsu', 'indica', 'Flower');
insert into strains (name, strain, category) values('Mazar I Sharif', 'indica', 'Flower');
insert into strains (name, strain, category) values('Mercury OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Misty Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('MK Ultra', 'indica', 'Flower');
insert into strains (name, strain, category) values('Mossimo OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Mr. Nice', 'indica', 'Flower');
insert into strains (name, strain, category) values('Negra 44', 'indica', 'Flower');
insert into strains (name, strain, category) values('Neptune Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Neptune OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Nordle', 'indica', 'Flower');
insert into strains (name, strain, category) values('Northern Lights', 'indica', 'Flower');
insert into strains (name, strain, category) values('Nuggetry OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Obama Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('OG Eddy Lepp', 'indica', 'Flower');
insert into strains (name, strain, category) values('Paris OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pennywise', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pineapple Thai', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pitbull', 'indica', 'Flower');
insert into strains (name, strain, category) values('Platinum Bubba', 'indica', 'Flower');
insert into strains (name, strain, category) values('Platinum Bubba Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Platinum Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Platinum OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Platinum Purple Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Plushberry', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pluto Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Popcorn Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pot of Gold', 'indica', 'Flower');
insert into strains (name, strain, category) values('Power Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Presidential OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pure Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pure OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Afghani', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Berry', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Candy', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Cream', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Dragon', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Goo', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Mr. Nice', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Nepal', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple OG Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Passion', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Tonic', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Urkle', 'indica', 'Flower');
insert into strains (name, strain, category) values('Purple Wreck', 'indica', 'Flower');
insert into strains (name, strain, category) values('Pre-98 Bubba Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('PVC OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Raspberry Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Red Dwarf', 'indica', 'Flower');
insert into strains (name, strain, category) values('Red Eye OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Redwood Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Remedy', 'indica', 'Flower');
insert into strains (name, strain, category) values('Rockstar', 'indica', 'Flower');
insert into strains (name, strain, category) values('Rockstar Master Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Romulan', 'indica', 'Flower');
insert into strains (name, strain, category) values('Seattle Blue', 'indica', 'Flower');
insert into strains (name, strain, category) values('Sensi Star', 'indica', 'Flower');
insert into strains (name, strain, category) values('Shark Shock', 'indica', 'Flower');
insert into strains (name, strain, category) values('Silverback Gorilla', 'indica', 'Flower');
insert into strains (name, strain, category) values('Skywalker', 'indica', 'Flower');
insert into strains (name, strain, category) values('Snow Monster', 'indica', 'Flower');
insert into strains (name, strain, category) values('Somango', 'indica', 'Flower');
insert into strains (name, strain, category) values('South Central LA', 'indica', 'Flower');
insert into strains (name, strain, category) values('Space Dawg', 'indica', 'Flower');
insert into strains (name, strain, category) values('Strawberry Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Sunshine Daydream', 'indica', 'Flower');
insert into strains (name, strain, category) values('Super Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Superman OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Super Skunk', 'indica', 'Flower');
insert into strains (name, strain, category) values('Tahoe OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Taliban Poison', 'indica', 'Flower');
insert into strains (name, strain, category) values('Tangerine Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('True OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('UW', 'indica', 'Flower');
insert into strains (name, strain, category) values('Vanilla Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('Violator Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('White Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('White OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Wonder Woman OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Woody Kush', 'indica', 'Flower');
insert into strains (name, strain, category) values('XXX 420', 'indica', 'Flower');
insert into strains (name, strain, category) values('XXX OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Yoda OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('Yumboldt', 'indica', 'Flower');
insert into strains (name, strain, category) values('Zombie OG', 'indica', 'Flower');
insert into strains (name, strain, category) values('ACDC', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Afwreck', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Alaska', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Avi-Dekel', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Banana Diesel', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Belladonna', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Champagne', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Diamond', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Dream', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Goo', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Haze', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Candyland', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cinderella 99', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Double Dream', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dream Star', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Duke Nukem', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Fruit Spirit', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Glass Slipper', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Green Dream', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hashplant Haze', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Fire', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Skunk', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Headbanger', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Head Cheese', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hippie Crippler', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hong Kong', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Huckleberry', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Humboldt', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('J1', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jack Haze', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jack''s Cleaner', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jack Widow', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jane Doe', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Juliet', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('K1', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lemon Kush', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lemon Wreck', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lethal Purple', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Loud Dream', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Midnight', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Mob Boss', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('NYC Diesel', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('OG Wreck', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Dream', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Haze', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pineapple Diesel', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Power Plant', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pure Power Plant', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Ice', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sapphire Star', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Silver Pearl', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Silver Surfer', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Smelliot', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Snowcap', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Cream', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Lemon OG', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Power', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Tsunami', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Stevie Wonder', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Strawberry Cough', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Strawberry Dream', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Superstar', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sweet Island Skunk', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Swiss Bliss', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tahoe OG Kush', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tangerine Haze', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Thai-Tanic', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('The Third Dimension', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('The Truth', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('Trainwreck', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Berry', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Fire OG', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Shark', 'sativa-hybrid', 'Flower');
insert into strains (name, strain, category) values('303 OG', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('707 Headband', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Afghanica', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('AK-48', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Albert Walker', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('BC Sweet Tooth', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Big Sky OG', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Big Wreck', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Bio-Jesus', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Domina', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Ice', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Mamba', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blockhead', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Bastard', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blueberry x Hash Plant', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Diesel', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Ivy', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Lights', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Magoo', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Venom', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Burmese Kush', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cali Gold', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Chemdawg 4', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Citrus Kush', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cold Creek Kush', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Confidential Cheese', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cotton Candy Kush', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Critical Bilbo', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Critical Haze', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dorit', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dr. Who', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Early Girl', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Elderberry Kush', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Erez', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Flowerbomb Kush', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('God''s Treat', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hells Angel OG', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Ice Cream', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jasmin or Yasmin', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lifesaver', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Little Devil', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('LVPK', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Manitoba Poison', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Master Skunk', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Matanuska Thunder Fuck', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Millennium', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Or', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Papaya', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pineapple Chunk', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pink Kush', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pink Pez', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Rascal OG', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Shiva Skunk', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Skywalker OG', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Snoop''s Dream', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Apple', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sugar Shack', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sunset Sherbert', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Supernova', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('The White', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tres Dawg', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Venom OG', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('Warlock', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Lightning', 'indica-hybrid', 'Flower');
insert into strains (name, strain, category) values('$100 OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('3 Kings', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Ace of Spades', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Afghan Big Bud', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Afghan Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Afghooey', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Agent Orange', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('AK-47', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Alien OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Alohaberry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Alpha OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Ambrosia', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Animal Cookies', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Apollo 11', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Apollo 13', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Appalachia', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Armageddon', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Atomic Northern Lights', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('A-Train', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Avalon', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Banana OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('BC Roadkill', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Berry White', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Big Buddha Cheese', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Bio-Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Dahlia', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Jack', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Tuna', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Velvet', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Black Widow', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blueberry Cheesecake', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blueberry Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blueberry Headband', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Boy', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Dragon', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Hawaiian', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Mystic', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Rhino', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Train', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Blue Widow', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Boggle Gum', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Bordello', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Boysenberry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Brains Damage', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Broke Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Bruce Banner #3', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Bubbleberry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Bubblegum', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Bubblegun', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('C13 Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cali Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Calm', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cannadential', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cannatonic', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Caramelicious', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Casey Jones', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cataract Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Champagne Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cheese', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Chem Crush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Chemdawg', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Chernobyl', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cherry AK-47', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cherry Bomb', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cherry Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cherry Limeade', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cherry Pie', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Chiesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Chocolate Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cinex', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Colorado Chem', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Connie Chung', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Cookies and Cream', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Crimea Blue', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dairy Queen', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Deadhead OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Diesel Duff', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dieseltonic', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dogwalker OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Donna OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dopium', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dreadlock', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dream Queen', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Durban Cheese', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Dutch Treat', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Euphoria', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Earth OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Earthquake', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Ed Rosenthal Super Bud', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('El-Na', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('El NiÃ±o', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Ewok', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Exodus Cheese', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Fire OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Flourish', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Fruity Pebbles', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Ghost OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Girl Scout Cookies', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Goldberry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Golden Goat', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Gorilla Glue #4', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Grand Hustle', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Grapefruit Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Grapefruit Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Grapefruit Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Grape God', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Grape Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Green Door Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Green Hornet', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Green Monster', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Green Queen', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Green Ribbon', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('G Stik "Orange"', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('G Stik "Verde"', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Guava Chem', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Guava Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Harlequin', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Harmony', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Punch', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hawaiian Thunder Fuck', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Headband', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Heavy Duty Fruity', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Himalayan Gold', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Hindu Skunk', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Holistic', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Holy Grail Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Ice', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jah Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jack Flash', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jack Frost', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jack Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jack the Ripper', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Jilly Bean', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Juicy Fruit', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Julius Caesar', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Kahuna', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Key Lime Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Khola', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Killer Queen', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Kimbo Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('King Kong', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Kushage', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Kushashima', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Kushberry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('LA Jack', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lambo OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('LAPD', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('LA Woman', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lavender', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lemon Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lemon Drop', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lemon Skunk', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lemon Walker OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Liberty Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lowryder', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('LSD', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Lucky Charms', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('M-39', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Mad Dog', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Mango Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Maui Berry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Martian Mean Green', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Master Yoda', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Medicine Man', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Mendocino Purps', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Mother''s Helper', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Nebula', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Neville''s Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Northern Lights #5', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Northern Skunk', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Odyssey', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('OG Diesel Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('OGiesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('OG Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('OG Poison', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('OG Shark', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Old Lyme Connecticut OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Bud', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Crush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Skunk', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Orange Velvet', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Organic Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('P-91', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Permafrost', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pineapple', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pineapple Express', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Pineapple Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Platinum Girl Scout Cookies', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple AK-47', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Arrow', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Dream', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Hashplant', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Jack', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Princess', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Sage', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Sour Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Trainwreck', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Purple Voodoo', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Qrazy Train', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Quebec Gold', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Querkle', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Rainbow', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Recon', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Red Cherry Berry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Redding OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Richie Rich', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Rocklock', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Romping Goddess', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Romulan Grapefruit', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Royal Dwarf', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Royal Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Russian Rocket Fuel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('SAGE', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Saturn OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('SFV OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sharksbreath', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Shiatsu Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Shishkaberry', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Shoreline', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sierra Mist', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Skunky Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sky Dog', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Snow White', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Cheese', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Dream', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Grape', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Grapes', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Jilly', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sour OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Space Bomb', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Space Queen', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Stardawg', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Starry Night', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Strawberry Banana', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Strawberry Diesel', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Super Blue Dream', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Super Lemon Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Super Sour Widow', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sweet Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Sweet Tooth', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tangerine Dream', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Thaidal Wave', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('THC Bomb', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('The Flav', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('The Void', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Thin Mint Girl Scout Cookies', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tiger Woods', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tranquil', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Trident', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Trifecta', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tropicali', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Tropical Tang', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('UK Cheese', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Unwind', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Verde Electric', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Waldo', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Walrus Kush', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Dawg', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Fire Alien OG', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Queen', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Rhino', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Russian', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Widow', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('White Zombie', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Willy''s Wonder', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Wonder Haze', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Wonder Woman', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('Wonka''s Bubblicious', 'mixed-hybrid', 'Flower');
insert into strains (name, strain, category) values('XJ-13', 'mixed-hybrid', 'Flower');
